little changes to scripts

diff --git a/bin/brightnessdunst b/bin/brightnessdunst
--- a/bin/brightnessdunst
+++ b/bin/brightnessdunst
@@ -1,5 +1,5 @@
 #!/usr/bin/env ksh
-
+#
 # You can call this script like this:
 # $ ./brightnessControl.sh up
 # $ ./brightnessControl.sh down
@@ -8,29 +8,40 @@
 # https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
 # https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a
 
-function get_brightness {
+ICON="preferences-system-brightness-lock"
+NOTIFICATION_ID="5555"
+INCREMENT="10%"
+
+get_brightness() {
   brightnessctl get
 }
 
-function send_notification {
-  icon="preferences-system-brightness-lock"
-  brightness=$(get_brightness)
-  # Make the bar with the special character ─ (it's not dash -)
-  # https://en.wikipedia.org/wiki/Box-drawing_character
-  bar=$(seq -s "─" 0 $((brightness / 150)) | sed 's/[0-9]//g')
-  # Send the notification
-  dunstify -i "$icon" -r 5555 -u normal "    $bar"
+send_notification() {
+  local brightness="$1"
+  local bar=$(seq -s "─" 0 $((brightness / 105)) | sed 's/[0-9]//g')
+  dunstify -i "$ICON" -r "$NOTIFICATION_ID" -u normal "$bar"
 }
 
+increase_brightness() {
+  brightnessctl set "+$INCREMENT"
+}
+
+decrease_brightness() {
+  brightnessctl set "$INCREMENT-"
+}
+
+# Main
 case $1 in
   up)
-    # increase the backlight by 10%
-    brightnessctl set +10%
-    send_notification
+    increase_brightness
     ;;
   down)
-    # decrease the backlight by 10%
-    brightnessctl set 10%-
-    send_notification
+    decrease_brightness
+    ;;
+  *)
+    echo "Invalid argument. Usage: $0 [up|down]"
+    exit 1
     ;;
 esac
+
+send_notification "$(get_brightness)"
