little changes to formatting
Former-commit-id: 9f177e4b5a6a98e5671bc4e7ad7f903f9ddf7ec8

diff --git a/bin/brightnessdunst b/bin/brightnessdunst
--- a/bin/brightnessdunst
+++ b/bin/brightnessdunst
@@ -9,35 +9,35 @@ NOTIFICATION_ID="5555"
 INCREMENT="10%"
 
 get_brightness() {
-	awk -v current="$(brightnessctl get)" -v max="$(brightnessctl max)" 'BEGIN { printf "%.0f\n", (current / max) * 100 }'
+  awk -v current="$(brightnessctl get)" -v max="$(brightnessctl max)" 'BEGIN { printf "%.0f\n", (current / max) * 100 }'
 }
 
 send_notification() {
-	brightness="$1"
-	progressbar "$brightness"
-	dunstify -r "$NOTIFICATION_ID" -u normal -t 1 ""
+  brightness="$1"
+  progressbar "$brightness"
+  dunstify -r "$NOTIFICATION_ID" -u normal -t 1 ""
 }
 
 increase_brightness() {
-	brightnessctl set "+$INCREMENT"
+  brightnessctl set "+$INCREMENT"
 }
 
 decrease_brightness() {
-	brightnessctl set "$INCREMENT-"
+  brightnessctl set "$INCREMENT-"
 }
 
 # Main
 case $1 in
-	up)
-		increase_brightness
-		;;
-	down)
-		decrease_brightness
-		;;
-	*)
-		echo "Invalid argument. Usage: $0 [up|down]"
-		exit 1
-		;;
+  up)
+    increase_brightness
+    ;;
+  down)
+    decrease_brightness
+    ;;
+  *)
+    echo "Invalid argument. Usage: $0 [up|down]"
+    exit 1
+    ;;
 esac
 
 send_notification "$(get_brightness)"
diff --git a/bin/cycle_ws b/bin/cycle_ws
--- a/bin/cycle_ws
+++ b/bin/cycle_ws
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 is_workspace_non_empty() {
-	workspace=$1
-	window_count=$(xdotool search --desktop "$workspace" '' 2>/dev/null | wc -l)
-	[ "$window_count" -gt 0 ]
+  workspace=$1
+  window_count=$(xdotool search --desktop "$workspace" '' 2>/dev/null | wc -l)
+  [ "$window_count" -gt 0 ]
 }
 
 # Get the current workspace and total workspaces
@@ -12,16 +12,16 @@ total_workspaces=$(xdotool get_num_desktops)
 
 # Define the direction based on the input argument
 case "$1" in
-next)
-	increment=1
-	;;
-prev)
-	increment=-1
-	;;
-*)
-	echo "Invalid argument. Please specify either 'next' or 'prev'."
-	exit 1
-	;;
+  next)
+    increment=1
+    ;;
+  prev)
+    increment=-1
+    ;;
+  *)
+    echo "Invalid argument. Please specify either 'next' or 'prev'."
+    exit 1
+    ;;
 esac
 
 # Calculate the target workspace
@@ -29,8 +29,8 @@ target_workspace=$(((current_workspace + increment + total_workspaces) % total_w
 
 # Loop until we find a non-empty workspace or we reach the starting point again
 while ! is_workspace_non_empty "$target_workspace" && [ "$target_workspace" -ne "$current_workspace" ]; do
-	# Move to the next or previous workspace
-	target_workspace=$(((target_workspace + increment + total_workspaces) % total_workspaces))
+  # Move to the next or previous workspace
+  target_workspace=$(((target_workspace + increment + total_workspaces) % total_workspaces))
 done
 
 # Switch to the non-empty workspace
