assorted changes
Former-commit-id: a3a133fde22427ae464765155bfb75638930f7fa

diff --git a/bin/cycle_ws b/bin/cycle_ws
--- a/bin/cycle_ws
+++ b/bin/cycle_ws
@@ -12,23 +12,26 @@ total_workspaces=$(xdotool get_num_desktops)
 
 # Define the direction based on the input argument
 case "$1" in
-  next)
-    increment=1
-    ;;
-  prev)
-    increment=-1
-    ;;
-  *)
-    echo "Invalid argument. Please specify either 'next' or 'prev'."
-    exit 1
-    ;;
+next)
+  increment=1
+  ;;
+prev)
+  increment=-1
+  ;;
+*)
+  echo "Invalid argument. Please specify either 'next' or 'prev'."
+  exit 1
+  ;;
 esac
 
 # Calculate the target workspace
 target_workspace=$(((current_workspace + increment + total_workspaces) % total_workspaces))
 
 # Loop until we find a non-empty workspace or we reach the starting point again
-while ! is_workspace_non_empty "$target_workspace" && [ "$target_workspace" -ne "$current_workspace" ]; do
+while
+  ! is_workspace_non_empty "$target_workspace"
+  \  && [ "$target_workspace" -ne "$current_workspace" ]
+do
   # Move to the next or previous workspace
   target_workspace=$(((target_workspace + increment + total_workspaces) % total_workspaces))
 done
