03-21-2024
Former-commit-id: e2f8f55e2818ce33d59d04d1098711abca7a6525

diff --git a/bin/scrrec b/bin/scrrec
--- a/bin/scrrec
+++ b/bin/scrrec
@@ -84,13 +84,13 @@ read -r W H X Y < <(select-region)
 
 # picom with blur and/or transparencies cause unbearable flickering in
 # recordings, so temporarily disable it.
-picom=
-if systemctl is-enabled --user picom >/dev/null; then
-  # systemctl --user stop picom
-  picom=1
-fi
-cleanup() { [[ $picom ]] && systemctl --user start picom; }
-trap cleanup EXIT
+# picom=
+# if systemctl is-enabled --user picom >/dev/null; then
+#   # systemctl --user stop picom
+#   picom=1
+# fi
+# cleanup() { [[ $picom ]] && systemctl --user start picom; }
+# trap cleanup EXIT
 
 # Let 'er rip
 recording-start "$1" "$X" "$Y" "$W" "$H"
